export const HOME_ACTIONS = {
    GET_INPUT_TO_SEARCH: 'HOME_GET_INPUT_TO_SEARCH',
    SEARCH_START: 'HOME_SEARCH_START',
    SEARCH_SUCESS: 'HOME_SEARCH_SUCESS',

};

export const API_KEY = "f12ba140";