export const HOME_ACTIONS = {
    GET_INPUT_TO_SEARCH: 'HOME_GET_INPUT_TO_SEARCH',
    SEARCH_START: 'HOME_SEARCH_START',
    SEARCH_SUCESS: 'HOME_SEARCH_SUCESS',
    SEARCH_FAILED: 'HOME_SEARCH_FAILED',
    SEARCH_REMOTE_FAILED: 'HOME_SEARCH_REMOTE_FAILED',
    ADD_TO_FAVORITES_LIST: 'HOME_ADD_TO_FAVORITES_LIST'
};

export const API_KEY = "f12ba140";