export const LOGIN_ACTIONS = {
    GET_USER_NAME: 'LOGIN_GET_USER_NAME',
    SET_USER_NAME_SUCESS: 'LOGIN_SET_USER_NAME_SUCESS',
    SET_USER_NAME_ERROR: 'LOGIN_SET_USER_NAME_ERROR',
    USER_LOGOUT: 'USER_LOGOUT'
}